# Local Kind-cluster variant of the Open5GS Custom Resource
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/open5gs-cr
  - ../../base/open5gs-subscribers
labels:
  - pairs:
      environment: local
