# ArgoCD Application for the Open5GS Operator Helm chart
# Installs the Operator controller into the open5gs namespace
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gs-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: open5gs-operator
    repoURL: registry-1.docker.io/gradiantcharts
    targetRevision: "1.0.7"
    helm:
      releaseName: open5gs-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: open5gs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
